[package]
name = "compiler-tools-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["extra-traits", "full"] }
quote = "1.0"
proc-macro2 = "1.0"
indexmap = "1.8"
regex = { version = "1.5" }

[dev-dependencies]
compiler-tools = { path = "../compiler-tools" }

[features]
